In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('utterance-data-with-labels-binary.csv')
df.head()
df.shape

(16977, 22)

In [3]:
for i in df:
    print(i)

ObsID
UtteranceID
TeacherID
TranscribedUtterance
IsQuestion
IsInstructionalUtterance
IsInstructionalStatement
IsDisciplinaryUtterance
IsDisciplinaryStatement
IsEvaluationFollowupIncluded
IsEvaluationElaborated
IsEvaluationValencePositive
CombinedAuthCogUptake
CogLevel
Uptake
IsGoalSpecified
IsDisciplinaryTermsPresent
IsInstructionalQuestion
IsDisciplinaryQuestion
IsStudentResponsePresent
Authenticity
IsSerialQuestion


In [4]:
df = df.drop(columns=['IsInstructionalStatement','IsDisciplinaryUtterance','IsDisciplinaryStatement','IsEvaluationFollowupIncluded','IsEvaluationValencePositive','CombinedAuthCogUptake','Uptake','IsInstructionalQuestion','IsDisciplinaryQuestion','IsStudentResponsePresent','IsSerialQuestion'])

In [5]:
#df = df.keep(columns=['IsQuestion','IsInstructionalUtterance','IsEvaluationElaborated','CogLevel','IsGoalSpecified','IsDisciplinaryTermsPresent','Authenticity'])

In [6]:
df.head()

ObsID  UtteranceID    TeacherID  \
0  sch01_tch01_03_19_18_period03            1  sch01_tch01   
1  sch01_tch01_03_19_18_period03          101  sch01_tch01   
2  sch01_tch01_03_19_18_period03          102  sch01_tch01   
3  sch01_tch01_03_19_18_period03          103  sch01_tch01   
4  sch01_tch01_03_19_18_period03          104  sch01_tch01   

                                TranscribedUtterance  IsQuestion  \
0                                   oh you mean the            1   
1                                thank you somebody            1   
2            so I'll need some some help reading it            0   
3  you will have died from walking across the str...           0   
4  get a very good soil goes into like that aware...           0   

   IsInstructionalUtterance  IsEvaluationElaborated  CogLevel  \
0                         1                       0         0   
1                         1                       0         0   
2                         1                       0         0   
3                         0                       0         0   
4                         1                       1         0   

   IsGoalSpecified  IsDisciplinaryTermsPresent  Authenticity  
0                0                           0             0  
1                0                           0             0  
2                0                           0             0  
3                0                           0             0  
4                0                           0             0

In [7]:
for i in df:
    print(i)

ObsID
UtteranceID
TeacherID
TranscribedUtterance
IsQuestion
IsInstructionalUtterance
IsEvaluationElaborated
CogLevel
IsGoalSpecified
IsDisciplinaryTermsPresent
Authenticity


In [8]:
df['labels'] = list(zip(df.IsQuestion.tolist(), df.IsInstructionalUtterance.tolist(), df.IsEvaluationElaborated.tolist(), df.CogLevel.tolist(), df.IsGoalSpecified.tolist(), df.IsDisciplinaryTermsPresent.tolist(), df.Authenticity.tolist()))
df['text'] = df['TranscribedUtterance'].apply(lambda x: x.replace('\n', ' '))

df.head()

ObsID  UtteranceID    TeacherID  \
0  sch01_tch01_03_19_18_period03            1  sch01_tch01   
1  sch01_tch01_03_19_18_period03          101  sch01_tch01   
2  sch01_tch01_03_19_18_period03          102  sch01_tch01   
3  sch01_tch01_03_19_18_period03          103  sch01_tch01   
4  sch01_tch01_03_19_18_period03          104  sch01_tch01   

                                TranscribedUtterance  IsQuestion  \
0                                   oh you mean the            1   
1                                thank you somebody            1   
2            so I'll need some some help reading it            0   
3  you will have died from walking across the str...           0   
4  get a very good soil goes into like that aware...           0   

   IsInstructionalUtterance  IsEvaluationElaborated  CogLevel  \
0                         1                       0         0   
1                         1                       0         0   
2                         1                       0         0   
3                         0                       0         0   
4                         1                       1         0   

   IsGoalSpecified  IsDisciplinaryTermsPresent  Authenticity  \
0                0                           0             0   
1                0                           0             0   
2                0                           0             0   
3                0                           0             0   
4                0                           0             0   

                  labels                                               text  
0  (1, 1, 0, 0, 0, 0, 0)                                   oh you mean the   
1  (1, 1, 0, 0, 0, 0, 0)                                thank you somebody   
2  (0, 1, 0, 0, 0, 0, 0)            so I'll need some some help reading it   
3  (0, 0, 0, 0, 0, 0, 0)  you will have died from walking across the str...  
4  (0, 1, 1, 0, 0, 0, 0)  get a very good soil goes into like that aware...

In [9]:
#df.tail()

In [10]:
from sklearn.model_selection import train_test_split
train_df, eval_df = train_test_split(df, test_size=0.2)

In [11]:
#This cell trains the model. Since, I already trained the model we don'y have to execute it.

# from simpletransformers.classification import MultiLabelClassificationModel
# model = MultiLabelClassificationModel('roberta', 'roberta-base', num_labels=18, args={'train_batch_size':2, 'gradient_accumulation_steps':16, 'learning_rate': 3e-5, 'num_train_epochs': 3, 'max_seq_length': 512})

#model.train_model(train_df)

In [12]:
# #To load a model a previously saved model instead of a default model, you can change the model_name to the path to a directory which contains a saved model.


from simpletransformers.classification import MultiLabelClassificationModel
model = MultiLabelClassificationModel('roberta', 'outputs/', num_labels=7, use_cuda=False)

In [105]:
model.model.roberta

RobertaModel(
  (embeddings): RobertaEmbeddings(
    (word_embeddings): Embedding(50265, 768, padding_idx=1)
    (position_embeddings): Embedding(514, 768, padding_idx=1)
    (token_type_embeddings): Embedding(1, 768)
    (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0): BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=768, out_features=768, bias=True)
            (key): Linear(in_features=768, out_features=768, bias=True)
            (value): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=768, out_features=768, bias=True)
            (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inpl

In [102]:
model.model.get_output_embeddings

<bound method PreTrainedModel.get_output_embeddings of RobertaForMultiLabelSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 768, padding_idx=1)
      (position_embeddings): Embedding(514, 768, padding_idx=1)
      (token_type_embeddings): Embedding(1, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, 

In [13]:
result, model_outputs, wrong_predictions = model.eval_model(eval_df)

In [14]:
#This is the evaluation results of the model
print(result)

{'LRAP': 0.974307074616263, 'eval_loss': 0.1880304925056065}


In [15]:
#The above evaluation command does not give us the predicted output so we run the following cells to get the predicted value and perform various types of performance tests.
#This is the test dataframe to be predicted
eval_df.head()

ObsID  UtteranceID    TeacherID  \
12624   sch03_tch01_05_25_18_period01           87  sch03_tch01   
2850    sch01_tch03_03_01_18_period03            7  sch01_tch03   
11469  sch02_tch07_05_10_18_period1-2            2  sch02_tch07   
14501   sch03_tch02_05_31_18_period06           38  sch03_tch02   
3800    sch01_tch04_04_30_18_period05          119  sch01_tch04   

                                    TranscribedUtterance  IsQuestion  \
12624  they're very stealthy what are some ways of de...           1   
2850                     observations about our high Q.            1   
11469  alright let's talk multiple choice for right n...           1   
14501            which is why I called you that Richard            0   
3800   okay so you name the errands okay got it so no...           1   

       IsInstructionalUtterance  IsEvaluationElaborated  CogLevel  \
12624                         1                       0         0   
2850                          1                       0         0   
11469                         1                       0         0   
14501                         0                       0         0   
3800                          1                       0         0   

       IsGoalSpecified  IsDisciplinaryTermsPresent  Authenticity  \
12624                0                           0             0   
2850                 0                           0             0   
11469                0                           0             0   
14501                0                           0             0   
3800                 0                           0             0   

                      labels  \
12624  (1, 1, 0, 0, 0, 0, 0)   
2850   (1, 1, 0, 0, 0, 0, 0)   
11469  (1, 1, 0, 0, 0, 0, 0)   
14501  (0, 0, 0, 0, 0, 0, 0)   
3800   (1, 1, 0, 0, 0, 0, 0)   

                                                    text  
12624  they're very stealthy what are some ways of de...  
2850                     observations about our high Q.   
11469  alright let's talk multiple choice for right n...  
14501            which is why I called you that Richard   
3800   okay so you name the errands okay got it so no...

In [17]:
to_predict = eval_df.text.apply(lambda x: x.replace('\n', ' ')).tolist()
preds, outputs = model.predict(to_predict)

#sub_df = pd.DataFrame(outputs, columns=['toxic','severe_toxic','obscene','threat','insult','identity_hate'])
sub_df = pd.DataFrame(outputs, columns=['IsQuestion','IsInstructionalUtterance','IsEvaluationElaborated','CogLevel','IsGoalSpecified','IsDisciplinaryTermsPresent','Authenticity'])

sub_df['ObsID'] = eval_df['ObsID']
sub_df = sub_df[['ObsID', 'IsQuestion','IsInstructionalUtterance','IsEvaluationElaborated','CogLevel','IsGoalSpecified','IsDisciplinaryTermsPresent','Authenticity']]

sub_df.to_csv('outputs/submission_our_project.csv', index=False)

In [36]:
print(preds)

[[1, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 1], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 1], [1, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 1, 0, 0], [0, 1, 0, 0, 0, 0, 0], [1, 1, 0, 0, 0, 0, 0], [0, 1, 0, 0, 0, 0, 0], [0, 1, 0, 

In [37]:
#These are raw outputs
print(outputs)

[[0.9572591  0.9772923  0.04569754 ... 0.01165632 0.01231542 0.10911819]
 [0.58074176 0.91072875 0.00557801 ... 0.02644288 0.01045797 0.03765972]
 [0.26564425 0.994364   0.03818808 ... 0.73527336 0.37676886 0.03633943]
 ...
 [0.9309688  0.91264284 0.01302162 ... 0.00927349 0.00750045 0.08269235]
 [0.0887578  0.8343118  0.00645955 ... 0.06963511 0.01015216 0.01018187]
 [0.9656183  0.98003674 0.1500809  ... 0.02192416 0.01911492 0.4733829 ]]


In [38]:
#This is the predicted dataframe on the test dataframe
sub_df.head()

ObsID  IsQuestion  IsInstructionalUtterance  \
0                            NaN    0.957259                  0.977292   
1                            NaN    0.580742                  0.910729   
2  sch01_tch01_03_19_18_period03    0.265644                  0.994364   
3                            NaN    0.405496                  0.688230   
4                            NaN    0.863481                  0.995449   

   IsEvaluationElaborated  CogLevel  IsGoalSpecified  \
0                0.045698  0.007452         0.011656   
1                0.005578  0.002500         0.026443   
2                0.038188  0.024543         0.735273   
3                0.013312  0.004372         0.004839   
4                0.081307  0.011113         0.094140   

   IsDisciplinaryTermsPresent  Authenticity  
0                    0.012315      0.109118  
1                    0.010458      0.037660  
2                    0.376769      0.036339  
3                    0.005922      0.022273  
4                    0.043693      0.114646

In [39]:
#Pre-Processing our predictions and true values to do Different performance tests

In [40]:
#--------------------------------------------------------#
import numpy as np
new_df= eval_df[['text','labels']]
new_df['preds'] = preds
#new_df['raw_ops'] = outputs
new_df['labels'] = np.array(new_df['labels'])

c:\users\farazalim\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.
c:\users\farazalim\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [41]:
new_df.head()

text  \
12624  they're very stealthy what are some ways of de...   
2850                     observations about our high Q.    
11469  alright let's talk multiple choice for right n...   
14501            which is why I called you that Richard    
3800   okay so you name the errands okay got it so no...   

                      labels                  preds  
12624  (1, 1, 0, 0, 0, 0, 0)  [1, 1, 0, 0, 0, 0, 0]  
2850   (1, 1, 0, 0, 0, 0, 0)  [1, 1, 0, 0, 0, 0, 0]  
11469  (1, 1, 0, 0, 0, 0, 0)  [0, 1, 0, 0, 1, 0, 0]  
14501  (0, 0, 0, 0, 0, 0, 0)  [0, 1, 0, 0, 0, 0, 0]  
3800   (1, 1, 0, 0, 0, 0, 0)  [1, 1, 0, 0, 0, 0, 0]

In [42]:
y_true=new_df['labels'].tolist()
y_true = np.asarray(y_true)
y_pred=new_df['preds'].tolist()
y_pred = np.asarray(y_pred)
y_scores = outputs
print(len(y_true))
print(len(y_pred))

3396
3396


In [43]:
print(y_true)

[[1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 1]]


In [44]:
print(y_pred)

[[1 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [0 1 0 ... 1 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]]


In [45]:
print(y_scores)

[[0.9572591  0.9772923  0.04569754 ... 0.01165632 0.01231542 0.10911819]
 [0.58074176 0.91072875 0.00557801 ... 0.02644288 0.01045797 0.03765972]
 [0.26564425 0.994364   0.03818808 ... 0.73527336 0.37676886 0.03633943]
 ...
 [0.9309688  0.91264284 0.01302162 ... 0.00927349 0.00750045 0.08269235]
 [0.0887578  0.8343118  0.00645955 ... 0.06963511 0.01015216 0.01018187]
 [0.9656183  0.98003674 0.1500809  ... 0.02192416 0.01911492 0.4733829 ]]


In [46]:
#For example, multi-class classification makes the assumption that each sample is assigned to one and only one label: a fruit can be either an apple or a pear but not both at the same time. Whereas, an instance of multi-label classification can be that a text might be about any of religion, politics, finance or education at the same time or none of these.
#https://medium.com/towards-artificial-intelligence/understanding-multi-label-classification-model-and-accuracy-metrics-1b2a8e2648ca
#Different performance tests

In [48]:
#subset accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_true, y_pred))

'''
Accuracy classification score.
In multilabel classification, this function computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.


There are some situations where we may go for an absolute accuracy ratio where measuring the exact combination of label predictions is important. 
It may sound relevant in the ‘Label power-set’ case. 
In the multi-label scenario, it is known as subset accuracy.
'''

0.5859835100117785


'\nAccuracy classification score.\nIn multilabel classification, this function computes subset accuracy: the set of labels predicted for a sample must exactly match the corresponding set of labels in y_true.\n\n\nThere are some situations where we may go for an absolute accuracy ratio where measuring the exact combination of label predictions is important. \nIt may sound relevant in the ‘Label power-set’ case. \nIn the multi-label scenario, it is known as subset accuracy.\n'

In [49]:
#Hamming-Loss (Example based measure):
from sklearn.metrics import hamming_loss
print(hamming_loss(y_true, y_pred))

'''The Hamming loss is the fraction of labels that are incorrectly predicted.

Instead of counting no of correctly classified data instance, Hamming Loss calculates loss generated in the bit string of class labels during prediction. 
It does XOR operation between the original binary string of class labels and predicted class labels for a data instance and calculates the average across the dataset. 
Its expression is given by

'''

0.0720595658758203


'The Hamming loss is the fraction of labels that are incorrectly predicted.\n\nInstead of counting no of correctly classified data instance, Hamming Loss calculates loss generated in the bit string of class labels during prediction. \nIt does XOR operation between the original binary string of class labels and predicted class labels for a data instance and calculates the average across the dataset. \nIts expression is given by\n\n'

In [50]:
import numpy as np
from sklearn.metrics import roc_auc_score
#print(roc_auc_score(y_true, y_pred))
print(roc_auc_score(y_true, y_scores))

'''
Compute Area Under the Receiver Operating Characteristic Curve (ROC AUC) from prediction scores.
Note: this implementation can be used with binary, multiclass and multilabel classification, but some restrictions apply (see Parameters).
'''

0.9149305625935319


'\nCompute Area Under the Receiver Operating Characteristic Curve (ROC AUC) from prediction scores.\nNote: this implementation can be used with binary, multiclass and multilabel classification, but some restrictions apply (see Parameters).\n'

In [51]:
import os
import csv
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

category = list(sub_df.columns.values)
categories = category[1:]
#print(category[1:])
#print(sub_df.iloc[:,1:])
sns.set(font_scale = 15)
plt.figure(figsize=(400,200))
ax= sns.barplot(categories, sub_df.iloc[:,1:].sum().values)

plt.title("Comments in each category", fontsize=300)
plt.ylabel('Number of comments', fontsize=300)
plt.xlabel('Comment Type ', fontsize=300)
#adding the text labels
rects = ax.patches
labels = sub_df.iloc[:,2:].sum().values
for rect, label in zip(rects, labels):
    height = rect.get_height()
    ax.text(rect.get_x() + rect.get_width()/2, height + 5, label, ha='center', va='bottom', fontsize=200)

In [52]:
#print(to_predict)

<h1>Now Let's play with our model. Enter random text and then execute the following two cells </h1>

In [70]:
preds_sample, outputs_sample = model.predict(["Did you do your HW"])
print(preds_sample)
print(len(preds_sample[0]))


[[1, 1, 0, 0, 0, 0, 0]]
7


In [71]:
j = ['IsQuestion','IsInstructionalUtterance','IsEvaluationElaborated','CogLevel','IsGoalSpecified','IsDisciplinaryTermsPresent','Authenticity']
for i in range(len(j)):
    if (preds_sample[0][i] == 1):
        print(j[i])

IsQuestion
IsInstructionalUtterance


In [72]:
#Add Confusion matrix

In [73]:
import numpy as np
from sklearn.metrics import multilabel_confusion_matrix

In [74]:
cm = multilabel_confusion_matrix(y_true, y_pred)
print(cm)

[[[2203  136]
  [ 300  757]]

 [[ 343  325]
  [ 157 2571]]

 [[3184   15]
  [ 169   28]]

 [[3293    4]
  [  91    8]]

 [[2989   80]
  [ 113  214]]

 [[3002   82]
  [  80  232]]

 [[3208    5]
  [ 156   27]]]


In [75]:
from sklearn.metrics import classification_report
print(classification_report(y_true,y_pred))

              precision    recall  f1-score   support

           0       0.85      0.72      0.78      1057
           1       0.89      0.94      0.91      2728
           2       0.65      0.14      0.23       197
           3       0.67      0.08      0.14        99
           4       0.73      0.65      0.69       327
           5       0.74      0.74      0.74       312
           6       0.84      0.15      0.25       183

   micro avg       0.86      0.78      0.82      4903
   macro avg       0.77      0.49      0.54      4903
weighted avg       0.84      0.78      0.79      4903
 samples avg       0.72      0.66      0.67      4903



c:\users\farazalim\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in samples with no predicted labels.
  'precision', 'predicted', average, warn_for)
c:\users\farazalim\appdata\local\programs\python\python36\lib\site-packages\sklearn\metrics\classification.py:1439: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in samples with no true labels.
  'recall', 'true', average, warn_for)


In [76]:
# labels=['IsQuestion','IsInstructionalUtterance','IsInstructionalStatement','IsDisciplinaryUtterance','IsDisciplinaryStatement','IsEvaluationFollowupIncluded','IsEvaluationElaborated','IsEvaluationValencePositive','CombinedAuthCogUptake','CogLevel','Uptake','IsGoalSpecified','IsDisciplinaryTermsPresent','IsInstructionalQuestion','IsDisciplinaryQuestion','IsStudentResponsePresent','Authenticity','IsSerialQuestion']
# multilabel_confusion_matrix(y_true, y_pred, labels=["IsQuestion","IsInstructionalUtterance",'IsInstructionalStatement','IsDisciplinaryUtterance','IsDisciplinaryStatement','IsEvaluationFollowupIncluded','IsEvaluationElaborated','IsEvaluationValencePositive','CombinedAuthCogUptake','CogLevel','Uptake','IsGoalSpecified','IsDisciplinaryTermsPresent','IsInstructionalQuestion','IsDisciplinaryQuestion','IsStudentResponsePresent','Authenticity','IsSerialQuestion'])

In [77]:
# from sklearn.metrics import plot_confusion_matrix

# disp = plot_confusion_matrix(classifier, X_test, y_test,
#                                  display_labels=class_names,
#                                  cmap=plt.cm.Blues

In [95]:
import numpy as np
from sklearn.metrics import roc_auc_score
#print(roc_auc_score(y_true, y_pred))
l = ['IsQuestion','IsInstructionalUtterance','IsEvaluationElaborated','CogLevel','IsGoalSpecified','IsDisciplinaryTermsPresent','Authenticity']
print("roc_auc_score for each label\n")
for i in range(7):
    #print(i)
    y_true_slice = y_true[:,i]
    y_scores_slice = y_scores[:,i]
    print(l[i])
    print(roc_auc_score(y_true_slice, y_scores_slice))
    print("\n")

roc_auc_score for each label

IsQuestion
0.9031481727913382


IsInstructionalUtterance
0.9013183310797759


IsEvaluationElaborated
0.9142022491165546


CogLevel
0.9344215586253803


IsGoalSpecified
0.9309046866016383


IsDisciplinaryTermsPresent
0.9597535044397886


Authenticity
0.8607654355002475


